#!/usr/bin/env python3
"""Build published-grounded classic Stratego defensive opening formations.

Coordinate system: row 0 = front (enemy side), row 3 = back; cols 0-9 left to right.
Piece keys use European/ISF ranks: 1=Marshal ... 10=Spy, plus BOMB and FLAG.
"""
from __future__ import annotations

from collections import Counter, defaultdict
import json
from pathlib import Path

COUNTS = {
    "1": 1,
    "2": 1,
    "3": 2,
    "4": 3,
    "5": 4,
    "6": 4,
    "7": 4,
    "8": 5,
    "9": 8,
    "10": 1,
    "BOMB": 6,
    "FLAG": 1,
}
FILL_ORDER = ["9", "7", "6", "5", "4", "3", "8", "10", "1", "2"]


def build(fixed: dict[tuple[int, int], str], name: str) -> list[list[str]]:
    board: list[list[str | None]] = [[None] * 10 for _ in range(4)]
    for (r, c), p in fixed.items():
        if board[r][c] is not None:
            raise AssertionError(f"{name}: collide {(r, c)}")
        board[r][c] = p
    used = Counter(p for row in board for p in row if p)
    for p, n in used.items():
        if n > COUNTS[p]:
            raise AssertionError(f"{name}: overplaced {p}: {n}")
    need: list[str] = []
    for p, n in COUNTS.items():
        need.extend([p] * (n - used[p]))
    empties = [(r, c) for r in range(4) for c in range(10) if board[r][c] is None]
    if len(empties) != len(need):
        raise AssertionError(f"{name}: empties {len(empties)} need {len(need)}")
    priority = {p: i for i, p in enumerate(FILL_ORDER)}
    need_sorted = sorted(need, key=lambda p: priority.get(p, 50))
    for (r, c), p in zip(empties, need_sorted):
        board[r][c] = p
    flat = [board[r][c] for r in range(4) for c in range(10)]
    if Counter(flat) != COUNTS:
        raise AssertionError(f"{name}: {Counter(flat)}")
    return board  # type: ignore[return-value]


def to_placements(board: list[list[str]]) -> dict[str, list[list[int]]]:
    d: dict[str, list[list[int]]] = defaultdict(list)
    for r in range(4):
        for c in range(10):
            d[board[r][c]].append([r, c])
    return {k: sorted(v) for k, v in sorted(d.items())}


def F(*pairs: tuple[int, int, str]) -> dict[tuple[int, int], str]:
    return {(r, c): p for r, c, p in pairs}


SPECS: list[tuple[str, str, dict[tuple[int, int], str], list[str]]] = [
    (
        "Flag Corner Defense",
        "Classic corner Flag with a two-Bomb seal (Ed Collins; UltraBoardGames 'Bombing the Flag' / 'The Corner'). Spare Bombs form an opposite-corner lure; Miners on the back ranks; Marshal/General split with Spy near General; Scouts mixed front (early warning) and rear (endgame).",
        F(
            (3, 0, "FLAG"),
            (3, 1, "BOMB"),
            (2, 0, "BOMB"),
            (3, 8, "BOMB"),
            (3, 9, "BOMB"),
            (2, 9, "BOMB"),
            (1, 4, "BOMB"),
            (2, 1, "7"),
            (3, 2, "7"),
            (3, 3, "8"),
            (3, 4, "8"),
            (3, 5, "8"),
            (2, 3, "8"),
            (2, 4, "8"),
            (1, 2, "1"),
            (1, 7, "2"),
            (2, 7, "10"),
            (0, 0, "9"),
            (0, 3, "9"),
            (0, 5, "9"),
            (0, 9, "9"),
            (3, 6, "9"),
            (3, 7, "9"),
        ),
        [
            "https://www.edcollins.com/stratego/stratego-tips.htm",
            "https://www.ultraboardgames.com/stratego/flag-placement.php",
            "https://ultraboardgames.com/stratego/bomb-placement.php",
        ],
    ),
    (
        "Lake-Back Three-Bomb Surround",
        "Most popular tournament Flag seat: back row behind a lake approach, enclosed by three Bombs (Invincible/de Boer thesis; UltraBoardGames middling back row). Flank defenders and rear Miners; high pieces central for multi-lane defense.",
        F(
            (3, 2, "FLAG"),
            (3, 1, "BOMB"),
            (3, 3, "BOMB"),
            (2, 2, "BOMB"),
            (3, 9, "BOMB"),
            (2, 9, "BOMB"),
            (2, 5, "BOMB"),
            (2, 1, "7"),
            (2, 3, "7"),
            (3, 4, "8"),
            (3, 5, "8"),
            (3, 6, "8"),
            (3, 7, "8"),
            (2, 4, "8"),
            (1, 4, "1"),
            (1, 6, "2"),
            (2, 6, "10"),
            (0, 0, "9"),
            (0, 1, "9"),
            (0, 4, "9"),
            (0, 5, "9"),
            (0, 8, "9"),
            (0, 9, "9"),
        ),
        [
            "Invincible thesis (Vincent de Boer, 2007)",
            "https://www.ultraboardgames.com/stratego/flag-placement.php",
            "https://www.edcollins.com/stratego/stratego-tips.htm",
        ],
    ),
    (
        "Two-Wave Corner (Double Bomb Defense)",
        "Cliff Peshek's Double Bomb Defense / UltraBoardGames & SpruceCrafts Two-Wave Corner: Flag in the corner; inner Bomb ring plus outer diagonal Bomb wave; Sergeants/Lieutenants between waves to kill Miners after the first defuse. Often needs 2–4 Miners to crack.",
        F(
            (3, 0, "FLAG"),
            (0, 0, "BOMB"),
            (1, 1, "BOMB"),
            (2, 0, "BOMB"),
            (2, 2, "BOMB"),
            (3, 1, "BOMB"),
            (3, 3, "BOMB"),
            (1, 0, "7"),
            (2, 1, "7"),
            (3, 2, "7"),
            (0, 1, "6"),
            (1, 2, "6"),
            (2, 3, "6"),
            (3, 6, "8"),
            (3, 7, "8"),
            (3, 8, "8"),
            (3, 9, "8"),
            (2, 8, "8"),
            (1, 5, "1"),
            (1, 7, "2"),
            (2, 7, "10"),
            (0, 4, "9"),
            (0, 5, "9"),
            (0, 8, "9"),
            (0, 9, "9"),
        ),
        [
            "https://www.edcollins.com/stratego/stratego-tips.htm (Cliff Peshek)",
            "https://ultraboardgames.com/stratego/bomb-placement.php",
            "https://www.thesprucecrafts.com/stratego-bomb-placement-strategy-412528",
        ],
    ),
    (
        "Decoy Flagposts",
        "UltraBoardGames Decoy Flagposts + Wade Oliver: real Flag in one two-Bomb corner; mirrored Bomb fortress in the opposite corner with an expendable Lieutenant inside so a Miner breakthrough finds a trap, not the Flag.",
        F(
            (3, 0, "FLAG"),
            (3, 1, "BOMB"),
            (2, 0, "BOMB"),
            (2, 1, "6"),
            (3, 9, "BOMB"),
            (2, 9, "BOMB"),
            (2, 8, "6"),
            (2, 4, "BOMB"),
            (2, 5, "BOMB"),
            (3, 3, "8"),
            (3, 4, "8"),
            (3, 5, "8"),
            (3, 6, "8"),
            (3, 7, "8"),
            (1, 3, "1"),
            (1, 6, "2"),
            (2, 6, "10"),
            (0, 1, "9"),
            (0, 2, "9"),
            (0, 4, "9"),
            (0, 5, "9"),
            (0, 7, "9"),
            (0, 8, "9"),
        ),
        [
            "https://ultraboardgames.com/stratego/bomb-placement.php",
            "https://www.edcollins.com/stratego/stratego-tips.htm (Wade Oliver)",
        ],
    ),
    (
        "Bombs One Row Back",
        "UltraBoardGames/SpruceCrafts: all six Bombs on row 1 in the six open columns (0,1,4,5,8,9), screened by a movable front row. Forces enemy Miners forward early; Flag tucked back behind ranked pieces (no Bombs left for a Flag ring).",
        F(
            (1, 0, "BOMB"),
            (1, 1, "BOMB"),
            (1, 4, "BOMB"),
            (1, 5, "BOMB"),
            (1, 8, "BOMB"),
            (1, 9, "BOMB"),
            (3, 7, "FLAG"),
            (3, 6, "7"),
            (3, 8, "7"),
            (2, 7, "4"),
            (3, 0, "8"),
            (3, 1, "8"),
            (3, 2, "8"),
            (2, 0, "8"),
            (2, 1, "8"),
            (2, 4, "1"),
            (2, 5, "2"),
            (2, 6, "10"),
            (0, 0, "9"),
            (0, 1, "9"),
            (0, 4, "9"),
            (0, 5, "9"),
            (0, 8, "9"),
            (0, 9, "9"),
        ),
        [
            "https://ultraboardgames.com/stratego/bomb-placement.php",
            "https://www.thesprucecrafts.com/stratego-bomb-placement-strategy-412528",
        ],
    ),
    (
        "Front Row Blocked",
        "UltraBoardGames: Flag on the front row behind a lake (here col 3) so frontal approach is water-blocked. Bombs used as dual back-corner decoy flagposts; Marshal/General nearby against side approaches.",
        F(
            (0, 3, "FLAG"),
            (0, 2, "7"),
            (0, 4, "4"),
            (3, 0, "BOMB"),
            (3, 1, "BOMB"),
            (2, 0, "BOMB"),
            (3, 8, "BOMB"),
            (3, 9, "BOMB"),
            (2, 9, "BOMB"),
            (3, 4, "8"),
            (3, 5, "8"),
            (3, 6, "8"),
            (2, 4, "8"),
            (2, 5, "8"),
            (1, 3, "1"),
            (1, 5, "2"),
            (1, 6, "10"),
            (0, 0, "9"),
            (0, 1, "9"),
            (0, 5, "9"),
            (0, 8, "9"),
            (0, 9, "9"),
        ),
        ["https://www.ultraboardgames.com/stratego/flag-placement.php"],
    ),
    (
        "X of Bombs",
        "StackExchange ('Stratego Master'): Bombs in an X; Flag below the center Bomb; Marshal right of center, Colonel left, Major above; extra Majors flanking the bottom X corners. Dense geometric Flag fort.",
        F(
            (1, 3, "BOMB"),
            (1, 5, "BOMB"),
            (2, 4, "BOMB"),
            (3, 3, "BOMB"),
            (3, 5, "BOMB"),
            (2, 2, "BOMB"),
            (3, 4, "FLAG"),
            (2, 5, "1"),
            (2, 3, "3"),
            (1, 4, "4"),
            (3, 2, "4"),
            (3, 6, "4"),
            (1, 6, "2"),
            (1, 7, "10"),
            (3, 0, "8"),
            (3, 1, "8"),
            (3, 7, "8"),
            (3, 8, "8"),
            (3, 9, "8"),
            (0, 0, "9"),
            (0, 2, "9"),
            (0, 4, "9"),
            (0, 5, "9"),
            (0, 7, "9"),
            (0, 9, "9"),
        ),
        [
            "https://boardgames.stackexchange.com/questions/221/what-are-good-placement-strategies-for-stratego"
        ],
    ),
    (
        "Diagonal Pyramid",
        "StackExchange (Andrew Vandever): pyramid/diagonal Bomb cluster protecting a mid-back Flag, backed by Sergeants (7s) to punish Miners after a defuse.",
        F(
            (3, 4, "FLAG"),
            (3, 3, "BOMB"),
            (3, 5, "BOMB"),
            (2, 3, "BOMB"),
            (2, 5, "BOMB"),
            (1, 4, "BOMB"),
            (2, 4, "BOMB"),
            (3, 2, "7"),
            (3, 6, "7"),
            (2, 2, "7"),
            (2, 6, "7"),
            (3, 0, "8"),
            (3, 1, "8"),
            (3, 7, "8"),
            (3, 8, "8"),
            (3, 9, "8"),
            (1, 2, "1"),
            (1, 6, "2"),
            (1, 7, "10"),
            (0, 0, "9"),
            (0, 1, "9"),
            (0, 3, "9"),
            (0, 5, "9"),
            (0, 7, "9"),
            (0, 8, "9"),
        ),
        [
            "https://boardgames.stackexchange.com/questions/221/what-are-good-placement-strategies-for-stratego (Andrew Vandever)"
        ],
    ),
    (
        "Corner Fortress",
        "Accolade 1990 named setup (Ed Collins archive): diagonal Bomb line with nestled Sergeants shielding a corner Flag; Scouts across the front; high officers grouped on battle alert away from the fortress.",
        F(
            (3, 0, "FLAG"),
            (3, 1, "BOMB"),
            (2, 0, "BOMB"),
            (2, 1, "BOMB"),
            (1, 0, "BOMB"),
            (1, 2, "BOMB"),
            (3, 2, "BOMB"),
            (2, 2, "7"),
            (1, 1, "7"),
            (3, 3, "7"),
            (0, 2, "7"),
            (0, 0, "9"),
            (0, 1, "9"),
            (0, 4, "9"),
            (0, 5, "9"),
            (0, 6, "9"),
            (0, 7, "9"),
            (0, 8, "9"),
            (0, 9, "9"),
            (1, 5, "1"),
            (1, 6, "2"),
            (1, 4, "3"),
            (1, 7, "3"),
            (2, 7, "10"),
            (3, 6, "8"),
            (3, 7, "8"),
            (3, 8, "8"),
            (3, 9, "8"),
            (2, 8, "8"),
        ),
        ["https://edcollins.com/stratego/stratego-piece-setups.htm (Accolade 1990)"],
    ),
    (
        "Shield Defense",
        "Accolade 1990: Flag wrapped in a central Bomb shield; Marshal, General, and Scouts occupy forward posts; Colonels/Majors just behind; Miners held in reserve on the flanks/rear.",
        F(
            (3, 4, "FLAG"),
            (3, 3, "BOMB"),
            (3, 5, "BOMB"),
            (2, 4, "BOMB"),
            (2, 3, "BOMB"),
            (2, 5, "BOMB"),
            (1, 4, "BOMB"),
            (0, 3, "1"),
            (0, 6, "2"),
            (0, 0, "9"),
            (0, 1, "9"),
            (0, 4, "9"),
            (0, 5, "9"),
            (0, 8, "9"),
            (0, 9, "9"),
            (1, 2, "3"),
            (1, 7, "3"),
            (1, 1, "4"),
            (1, 3, "4"),
            (1, 6, "4"),
            (3, 0, "8"),
            (3, 1, "8"),
            (3, 8, "8"),
            (3, 9, "8"),
            (2, 0, "8"),
            (2, 6, "10"),
        ),
        ["https://edcollins.com/stratego/stratego-piece-setups.htm (Accolade 1990)"],
    ),
    (
        "Shoreline Bluff",
        "Accolade 1990 defensive deception: Flag placed forward near the lake shoreline; a Bomb on each flank; remaining Bombs scattered through the lines; high officers beside the Flag; Scouts held in the rear as endgame reserves.",
        F(
            (0, 4, "FLAG"),
            (0, 0, "BOMB"),
            (0, 9, "BOMB"),
            (1, 2, "BOMB"),
            (1, 5, "BOMB"),
            (2, 3, "BOMB"),
            (2, 7, "BOMB"),
            (0, 3, "1"),
            (0, 5, "3"),
            (1, 4, "2"),
            (1, 3, "10"),
            (3, 0, "9"),
            (3, 1, "9"),
            (3, 2, "9"),
            (3, 3, "9"),
            (3, 6, "9"),
            (3, 7, "9"),
            (3, 8, "9"),
            (3, 9, "9"),
            (3, 4, "8"),
            (3, 5, "8"),
            (2, 4, "8"),
            (2, 5, "8"),
            (2, 0, "8"),
        ),
        ["https://edcollins.com/stratego/stratego-piece-setups.htm (Accolade 1990)"],
    ),
    (
        "Early Warning!",
        "Accolade 1990: five of six Bombs clustered around the Flag; Scouts and top officers ready forward; Miners poised on one side; Captains populate rear ranks away from the Bomb nest.",
        F(
            (3, 1, "FLAG"),
            (3, 0, "BOMB"),
            (3, 2, "BOMB"),
            (2, 0, "BOMB"),
            (2, 1, "BOMB"),
            (2, 2, "BOMB"),
            (1, 8, "BOMB"),
            (0, 3, "9"),
            (0, 4, "9"),
            (0, 5, "9"),
            (0, 6, "9"),
            (0, 0, "9"),
            (0, 9, "9"),
            (0, 1, "1"),
            (0, 7, "2"),
            (0, 2, "3"),
            (0, 8, "3"),
            (2, 7, "8"),
            (2, 8, "8"),
            (2, 9, "8"),
            (3, 8, "8"),
            (3, 9, "8"),
            (3, 4, "5"),
            (3, 5, "5"),
            (3, 6, "5"),
            (3, 7, "5"),
            (3, 3, "6"),
            (2, 3, "6"),
            (2, 4, "6"),
            (2, 5, "6"),
            (1, 1, "10"),
        ),
        ["https://edcollins.com/stratego/stratego-piece-setups.htm (Accolade 1990)"],
    ),
    (
        "Man the Barricades",
        "Accolade 1990: pairs of Bombs nestled in the front lines as barricades; Marshal personally guards a corner Flag; high officers form the forward alignment; Miners and Scouts wait in reserve.",
        F(
            (3, 0, "FLAG"),
            (2, 0, "1"),
            (0, 1, "BOMB"),
            (0, 2, "BOMB"),
            (0, 6, "BOMB"),
            (0, 7, "BOMB"),
            (1, 4, "BOMB"),
            (1, 5, "BOMB"),
            (0, 3, "2"),
            (0, 4, "3"),
            (0, 5, "3"),
            (0, 8, "4"),
            (3, 6, "8"),
            (3, 7, "8"),
            (3, 8, "8"),
            (3, 9, "8"),
            (2, 8, "8"),
            (3, 2, "9"),
            (3, 3, "9"),
            (3, 4, "9"),
            (3, 5, "9"),
            (2, 6, "9"),
            (2, 7, "9"),
            (2, 9, "9"),
            (1, 9, "9"),
            (2, 1, "10"),
        ),
        ["https://edcollins.com/stratego/stratego-piece-setups.htm (Accolade 1990)"],
    ),
    (
        "Side-Seal Center Stack",
        "Philip van Dijk (Ed Collins tips): seal the side lanes with Bombs so early fights funnel to the center; stack Marshal/General/Colonels/Majors centrally; Sergeants beside the Flag to kill breakthrough Miners.",
        F(
            (3, 4, "FLAG"),
            (3, 3, "7"),
            (3, 5, "7"),
            (1, 0, "BOMB"),
            (1, 1, "BOMB"),
            (1, 8, "BOMB"),
            (1, 9, "BOMB"),
            (2, 0, "BOMB"),
            (2, 9, "BOMB"),
            (1, 4, "1"),
            (1, 5, "2"),
            (1, 3, "3"),
            (1, 6, "3"),
            (2, 4, "4"),
            (2, 5, "4"),
            (2, 3, "4"),
            (1, 2, "10"),
            (3, 0, "8"),
            (3, 1, "8"),
            (3, 8, "8"),
            (3, 9, "8"),
            (3, 2, "8"),
            (0, 2, "9"),
            (0, 3, "9"),
            (0, 4, "9"),
            (0, 5, "9"),
            (0, 6, "9"),
            (0, 7, "9"),
            (2, 1, "6"),
            (2, 2, "6"),
            (2, 6, "6"),
            (2, 7, "6"),
        ),
        ["https://www.edcollins.com/stratego/stratego-tips.htm (Philip van Dijk)"],
    ),
    (
        "Bombed-in Sergeant Misdirection",
        "Dan Burkhart (Ed Collins): corner Bomb–Sergeant–Flag puzzle so Miners usually defuse the wrong Bomb and die to a Sergeant, then abandon the sector; mirrored Bomb–Sergeant decoy on the far wing; high pieces free in the center.",
        F(
            (3, 0, "BOMB"),
            (3, 1, "FLAG"),
            (3, 2, "BOMB"),
            (2, 1, "BOMB"),
            (2, 0, "7"),
            (3, 9, "BOMB"),
            (2, 9, "BOMB"),
            (3, 8, "BOMB"),
            (2, 8, "7"),
            (1, 5, "1"),
            (1, 6, "2"),
            (1, 4, "3"),
            (1, 7, "3"),
            (2, 5, "10"),
            (3, 4, "8"),
            (3, 5, "8"),
            (3, 6, "8"),
            (3, 7, "8"),
            (2, 4, "8"),
            (0, 0, "9"),
            (0, 2, "9"),
            (0, 4, "9"),
            (0, 5, "9"),
            (0, 7, "9"),
            (0, 9, "9"),
        ),
        ["https://www.edcollins.com/stratego/stratego-tips.htm (Dan Burkhart)"],
    ),
    (
        "Wheel of Danger",
        "Accolade 1990: odd mix of Scouts and Bombs on the forward lines; Flag encapsulated in a Bomb rectangle in the rear center; high officers waiting in reserve behind the scout/bomb screen.",
        F(
            (0, 1, "BOMB"),
            (0, 3, "BOMB"),
            (0, 6, "BOMB"),
            (0, 8, "BOMB"),
            (3, 3, "BOMB"),
            (3, 5, "BOMB"),
            (3, 4, "FLAG"),
            (0, 0, "9"),
            (0, 2, "9"),
            (0, 4, "9"),
            (0, 5, "9"),
            (0, 7, "9"),
            (0, 9, "9"),
            (2, 8, "1"),
            (2, 9, "2"),
            (2, 6, "3"),
            (2, 7, "3"),
            (2, 5, "10"),
            (3, 0, "8"),
            (3, 1, "8"),
            (3, 8, "8"),
            (3, 9, "8"),
            (2, 0, "8"),
        ),
        ["https://edcollins.com/stratego/stratego-piece-setups.htm (Accolade 1990)"],
    ),
    (
        "Triple Threat",
        "Accolade 1990: formidable Bomb array clotting the back row around the Flag; Miners held in reserve on row 2; high-ranking units and Scouts fill the front lines for immediate pressure while the rear is a Bomb wall.",
        F(
            (3, 3, "FLAG"),
            (3, 0, "BOMB"),
            (3, 1, "BOMB"),
            (3, 2, "BOMB"),
            (3, 4, "BOMB"),
            (3, 5, "BOMB"),
            (3, 6, "BOMB"),
            (2, 6, "8"),
            (2, 7, "8"),
            (2, 8, "8"),
            (2, 9, "8"),
            (3, 7, "8"),
            (0, 0, "9"),
            (0, 2, "9"),
            (0, 4, "9"),
            (0, 6, "9"),
            (0, 8, "9"),
            (0, 9, "9"),
            (3, 8, "9"),
            (3, 9, "9"),
            (0, 1, "1"),
            (0, 3, "2"),
            (0, 5, "3"),
            (0, 7, "3"),
            (1, 7, "10"),
        ),
        ["https://edcollins.com/stratego/stratego-piece-setups.htm (Accolade 1990)"],
    ),
    (
        "Double-Bomb Lane Seal",
        "BoardGames.SE (Tycho): pick one of the three lake-gap entrances and double-Bomb it shut so an even three-front attack stalls; the Miner that clears the lane is usually captured immediately. Flag protected separately toward the back.",
        F(
            (0, 3, "BOMB"),
            (0, 4, "BOMB"),
            (1, 3, "BOMB"),
            (1, 4, "BOMB"),
            (3, 5, "BOMB"),
            (2, 5, "BOMB"),
            (3, 4, "FLAG"),
            (3, 3, "7"),
            (2, 4, "7"),
            (2, 3, "7"),
            (1, 5, "3"),
            (1, 6, "2"),
            (1, 7, "10"),
            (2, 4, "1"),  # collide - fix below
        ),
        [
            "https://boardgames.stackexchange.com/questions/221/what-are-good-placement-strategies-for-stratego (Tycho)"
        ],
    ),
]


def main() -> None:
    # Fix Double-Bomb Lane Seal (had collision) by replacing last entry
    global SPECS
    specs = [s for s in SPECS if s[0] != "Double-Bomb Lane Seal"]
    specs.append(
        (
            "Double-Bomb Lane Seal",
            "BoardGames.SE (Tycho): pick one of the three lake-gap entrances and double-Bomb it shut so an even three-front attack stalls; the Miner that clears the lane is usually captured immediately. Flag protected separately toward the back.",
            F(
                (0, 3, "BOMB"),
                (0, 4, "BOMB"),
                (1, 3, "BOMB"),
                (1, 4, "BOMB"),
                (3, 5, "BOMB"),
                (2, 5, "BOMB"),
                (3, 4, "FLAG"),
                (3, 3, "7"),
                (2, 3, "7"),
                (2, 4, "1"),
                (1, 5, "3"),
                (1, 6, "2"),
                (1, 7, "10"),
                (3, 0, "8"),
                (3, 1, "8"),
                (3, 2, "8"),
                (3, 8, "8"),
                (3, 9, "8"),
                (0, 0, "9"),
                (0, 1, "9"),
                (0, 5, "9"),
                (0, 8, "9"),
                (0, 9, "9"),
            ),
            [
                "https://boardgames.stackexchange.com/questions/221/what-are-good-placement-strategies-for-stratego (Tycho)"
            ],
        )
    )

    out = []
    for name, desc, fixed, sources in specs:
        board = build(fixed, name)
        out.append(
            {
                "name": name,
                "description": desc,
                "sources": sources,
                "placements": to_placements(board),
            }
        )
        print(f"OK {name}")

    path = Path(__file__).resolve().parents[1] / "docs" / "defensive_formations.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(out, indent=2) + "\n")
    print(f"Wrote {len(out)} formations -> {path}")


if __name__ == "__main__":
    main()
